# Site
name: 'Answer AI Blog'
description: 'Answer AI Blog: AI for Everyone, Everywhere'
url: https://bilalmoten.github.io/blog
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
# baseurl: '/mundana-theme-jekyll'
disqus: 'Answer AI Blog'
email: 'support@answerai.tech'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    Answer AI Team:
      name:           Answer AI Team
      site:           https://www.answerai.tech
      avatar:         /assets/images/avatar1.jpg
      bio:            "This blog is maintained by the Answer AI team. We are a team of AI enthusiasts who are passionate about making AI content generation available to you guys so everyone  can use the latest AI technology to improve their content and their lives."
      email:          support@answerai.tech
      # twitter:        https://twitter.com/wowthemesnet

    # jane:
    #   name:           Jane
    #   site:           https://www.wowthemes.net
    #   avatar:         /assets/images/avatar2.jpg
    #   bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
    #   email:          fakemail@gmail.com
    #   twitter:        https://twitter.com/wowthemesnet
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Answer AI Team
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]